# Generated by Django 5.0.6 on 2024-05-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('Tel_number', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
